version: '3'
services:
  webapp:
    build: ./narad
    ports:
      - 8000:8000
    links:
      - postgres
      - redis
    volumes:
      - /tmp/static:/srv/www/static
      - /tmp/uploads:/srv/www/app/uploads
    environment:
      - DATABASE_URL=postgres://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@postgres:${POSTGRESQL_PORT}/postgres
      - DJANGO_SETTINGS_MODULE=narad.settings
      - WEBTIMEOUT=${WEBTIMEOUT}
      - PORT=8000
      - REDISGO_URL=redis://redis:6379
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - /tmp/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - /tmp/redis:/data
