FROM python:latest

ENV STATIC_ROOT /srv/www/static

WORKDIR /srv/www/app

RUN pip install pipenv

COPY manage.py .

COPY Pipfile .

COPY Pipfile.lock .

RUN pipenv install

# NOTE: This is custom hack especially for Heorku container registery
RUN pipenv lock -r > /tmp/requirements.txt

RUN pip install --no-cache-dir -q -r /tmp/requirements.txt

COPY narad narad

COPY product_manager product_manager

COPY start_web.sh .

CMD bash start_web.sh
