# Generated by Django 2.2.4 on 2019-08-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=None, max_length=200, null=None, primary_key=True, serialize=False, unique=True),
        ),
    ]
