# Generated by Django 2.2.4 on 2019-09-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0002_auto_20190829_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsAsCsvFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(upload_to='')),
            ],
        ),
    ]

