# Generated by Django 2.2.5 on 2019-09-02 12:52

from django.db import migrations
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0003_productsascsvfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
